### ISSUE TITLE
mounted 没执行

### ISSUE THREAD

**Issue by wanghaixu** [yodfz/m-dropload#4]
使用vuex，route;  在main.js中引入，在组件中使用。但mounted 函数根本没执行。
没报错。

**Comment by yodfz** [comment]
mounted函数没有执行是，因为你使用了vuex,触发是在data里面完成的。
你可以看一下，你的获取数据是在哪里进行的，就在哪里进行绑定。
或者你也可以等vue.@nexttick完成之后再绑定。

**Comment by yodfz** [comment]
建议查阅一下vue生命周期。这样你可以更加明白一些。

**Comment by wanghaixu** [comment]
谢谢答复！在组件的ready()函数中也不行吗？
应该很多人使用vuex,希望能有这个示例。

**Comment by yodfz** [comment]
vue 1.0.x 用的是ready() ,2.0.x的生命周期中,ready 改成了mounted,忘知悉。
demo是2.0.x版本

**Comment by wanghaixu** [comment]
我使用的是1.0
