### ISSUE TITLE
有考虑过把css外置吗？

### ISSUE THREAD

**Issue by gxy01** [yodfz/m-dropload#6]
本身css和js是分离的。内置css在js中，可以方便的引入这个库。但是实际开发过程中，基本都会自己处理css和js部分。css在开发中可能经过autoprefixer或者px2rem的转换才引入，即每个项目对css都有自己的处理。
现在内置css会比较容易引入。但是外置引入css，对于项目更灵活，耦合性会更好吧

**Comment by yodfz** [comment]
这个有过考虑，但是为了方便插件引入所以直接内置了。
另外。可以通过class强制控制
内置的CSS只是最低的控制显示效果而已
